version: '3.9'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  client:
    build: ./client
    command: ["sh", "-c", "npm run dev"]
    ports:
      - "5173:5173"
    volumes:
      - ./client:/client
      - /client/node_modules

    depends_on:
      - backend

  backend:
    build: ./backend
    command: ["sh", "-c", "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  data:
